### ISSUE TITLE
React Native Import Error

### ISSUE THREAD

**Issue by ponty96** [pusher/pusher-js#166]
![screen shot 2016-05-09 at 9 27 29 pm](https://cloud.githubusercontent.com/assets/11190968/15127119/140e9252-162d-11e6-84a3-919dc312d414.png)

Thats what i get after using this: `import Pusher from 'pusher-js/react-native';` in my code

**Comment by jackfranklin** [comment]
Have you tried the three debugging steps suggested above? Just to rule them out :)

**Comment by jackfranklin** [comment]
Oh wait, this is because we've merged all the stuff for 3.1 but it's not been put onto npm yet. This should be fixed tomorrow (although @jpatel531 can confirm) - in the mean time you could try depending on `pusher/pusher-js#master` and that should work, I think.

**Comment by jpatel531** [comment]
@ponty96 could you try this out? Jack's right - I merged it two days ago but could only make a release this morning

**Comment by jackfranklin** [comment]
@ponty96 just to be clear, 3.1 is now on npm.

**Comment by nik** [comment]
@jackfranklin i have 3.1, and i'm still getting: 

`Module not found: Error: Cannot resolve module 'react-native' in`

I've tried `rm -rf node_modules` and all that, including `--reset-cache`. not sure what the deal is

**Comment by jpatel531** [comment]
the build is looking for the 'react-native' module, but for some reason cannot find it. any ideas @jackfranklin . i've done this a fair few times, but not seen this

**Comment by jackfranklin** [comment]
I'm confused - is the issue here that the projects can't find the Pusher React Native build, or that the `require('react-native')` inside Pusher isn't working?

On the former the path should be `pusher-js/dist/react-native/pusher`, but I don't know about why a `require('react-native')` inside Pusher would fail.

@jpatel531 Does PusherJS have react-native as a dependency?

**Comment by jpatel531** [comment]
The former is correct. It doesn't have react-native as a dependency. The react-native distribution should just look to require('react-native') from the environment

**Comment by jackfranklin** [comment]
Got you - in hindsight it was entirely stupid to think Pusher should list it as a dependency.

**Comment by jpatel531** [comment]
I've just spun up a fresh app and it all seems fine. 

Also @nik - is there a reason it's looking at /Users/node_modules for dependencies, rather than your local node_modules ?

**Comment by nik** [comment]
@jpatel531 its looking at my local node modules. the `...` was just to leave out the unimportant paths, sorry for confusion

**Comment by jpatel531** [comment]
mmm how bizarre. which versions of node and react-native are you on?

**Comment by jackfranklin** [comment]
@nik would you be able to get an example proj on GitHub that recreates?

**Comment by nik** [comment]
@jpatel531 @jackfranklin you guys can probably close this issue. it was a "too much coding in one day" mistake on my end that magically happened to coincide with a recently closed issue. thanks for being so responsive about this.

**Comment by jackfranklin** [comment]
No worries! Feel free to comment again if it crops up.

**Comment by jpatel531** [comment]
I'm glad this is solved! Feel free to let us know what you end up building. Very welcome to get feedback on the react-native build, given that it's very new!

**Comment by ajpsp5** [comment]
I am getting **Cannot find module "react-native"** in my Ionic App.

I ran `npm install pusher-js --save` and trying to import with
```javascript
import { Pusher } from 'pusher-js/react-native';
```

How can import the library?

**Comment by hph** [comment]
@ajpsp5 It should be `import Pusher from 'pusher-js/react-native'`.
