### ISSUE TITLE
WebSocket is closed before the connection is established.

### ISSUE THREAD

**Issue by kaloraat** [pusher/pusher-js#274]
I keep getting this error: WebSocket connection to 'wss://ws-mt1.pusher.com/app/37e9ce9d011feefbd899?protocol=7&client=js&version=4.2.2&flash=false' failed: WebSocket is closed before the connection is established.

I am following <a href="https://pusher.com/tutorials/chat-laravel/">official chat app tutorial with laravel and pusher</a>. Even when I do not listen or use laravel Echo in the frontend (I am using React) I still get this error.. any help would be appreciated, thanks!

**Comment by kaloraat** [comment]
I fixed it by creating a fresh new app in the pusher dashboard. I also choose vanila js as frontend and php as backend while creating a new app.

**Comment by mohammedaktaa** [comment]
i have the sane issue but new app didn't solve it. doe you find any solution @kaloraat ??

**Comment by spruce-bruce** [comment]
I was getting this error during my initial "hello, world!" testing. Try setting the cluster explicitly:

```
const pusher = new Pusher('APPID', { 
  cluster: 'us2', // look up your cluster in your pusher app's dashboard
  encrypted: true 
});
```

**Comment by leesio** [comment]
@mohammedaktaa are you experiencing this issue?

**Comment by mohammedaktaa** [comment]
I solved it by creating new app in pusher and I put the cluster "eu" and the environment is php not laravel.
And in your is code you should put the cluster, try it .

**Comment by leesio** [comment]
Glad to hear you resolved your issue.

I'm going to close this issue now :)

**Comment by moesyzlack8** [comment]
i am having the same issue only i am also getting this error i have tried changing the cluster and creating a new pusher project with php and still no joy... any ideas?
/*error
================================================*/
app.js:39163 Uncaught TypeError: Cannot read property 'apply' of undefined
    at PrivateChannel.Dispatcher.emit (app.js:39163)
    at PrivateChannel.Channel.handleEvent (app.js:40826)
    at app.js:37694
    at ConnectionManager.Dispatcher.emit (app.js:39163)
    at message (app.js:45768)
    at Connection.Dispatcher.emit (app.js:39163)
    at message (app.js:40556)
    at TransportConnection.Dispatcher.emit (app.js:39163)
    at TransportConnection.onMessage (app.js:39060)
    at WebSocket.socket.onmessage (app.js:39077)

**Comment by onkar95** [comment]
same issue in react

**Comment by onkar95** [comment]
xbmb,cbnkf kffffffbg[https://pusher.com/tutorials/chat-laravel/](bjhbjhljurl)

**Comment by Turbotailz** [comment]
Just had this error happen randomly on all of our environments (using different app keys). Took us a while to realise it was because Pusher had downgraded us due to a failed credit card payment (no one was checking the inbox where the email was sent). So only max 100 people were able to connect, anyone outside this limit was getting this error.
