### ISSUE TITLE
Types not available for react native

### ISSUE THREAD

**Issue by chrisdrackett** [pusher/pusher-js#405]
**Do you want to request a *feature* or report a *bug*?**

Bug / Feature… not sure

**What is the current behavior?**

I've installed `pusher-js@5.0.3` and `@types/pusher-js@4.2.2` I tried with just pusher-js, but didn't get types. Based on this I almost didn't open an issue here as I thought maybe typescript support wasn't official. That being said I see work and issues around typescript so I decided to open this issue. 

When using

```js
import Pusher from 'pusher-js/react-native'
```

I get the following:

```
Could not find a declaration file for module 'pusher-js/react-native'. 'node_modules/pusher-js/react-native.js' implicitly has an 'any' type.
  If the 'pusher-js' package actually exposes this module, consider sending a pull request to amend 'https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/pusher-js`
```

**What is the expected behavior?**

Types work when using plain javascript and react-native.

**Comment by leesio** [comment]
When you say you "tried with just pusher-js, but didn't get types" could you confirm what you mean exactly?

Just so I can recreate the issue you're seeing?
Is the error message in your editor or is it from the typescript transpiler itself?

**Comment by chrisdrackett** [comment]
Sorry, basically it seems like the react-native version of pusher is missing types in `@types/pusher-js`. This issue probably does not belong in this repo, feel free to close if that is the case!

```
src/pusher.native.ts:1:20 - error TS7016: Could not find a declaration file for module 'pusher-js/react-native'. '/Users/cwd/src/calm/node_modules/pusher-js/react-native.js' implicitly has an 'any' type.
  Try `npm install @types/pusher-js` if it exists or add a new declaration (.d.ts) file containing `declare module 'pusher-js/react-native';`

1 import Pusher from 'pusher-js/react-native'
                     ~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by leesio** [comment]
Hey @chrisdrackett, I spent a bit of time working on typescript declarations for pusher-js recently. I added a commit which adds types to react-native for me.

In my experience react-native projects seem to have lots of variation, so I wonder whether you'd like to try out the version to see if it works for you? If it does, I'll be able to include it in a release soon.

The version is on #421 you can install it with 
```
npm install git+ssh://git@github.com:pusher/pusher-js#include-react-native-types
```

**Comment by leesio** [comment]
@chrisdrackett 👋 again. I just published a new version which includes the above change. Let me know if it solves your issue!

**Comment by chrisdrackett** [comment]
@leesio hm still seeing the following when importing in react native on 6.0.0:

```
Could not find a declaration file for module 'pusher-js/react-native'. '/Users/cwd/src/calm/node_modules/pusher-js/react-native.js' implicitly has an 'any' type.
  Try `npm install @types/pusher-js` if it exists or add a new declaration (.d.ts) file containing `declare module 'pusher-js/react-native';`
```

**Comment by chrisdrackett** [comment]
@leesio so I just installed your branch (include-react-native-types) and that does work (sorry for not trying it before). Seems like that is still needed in 6.0.0

**Comment by leesio** [comment]
I just pushed release 6.0.1 which includes the react-native types.

**Comment by special-character** [comment]
@leesio I think that the update might have caused an import issue with `pusher-js/react-native` looking in the wrong spot for dist. Do you think that is possible from this update?

Getting the error:

```
Unable to resolve module `./dist/react-native/pusher` from `../node_modules/pusher-js/react-native/index.js`
```

I looked at `pusher-js/react-native/index.js` and it has an import like this:

```
module.exports = require('./dist/react-native/pusher');
```

The dist folder for me on a clean install is actually up a level in the `pusher-js` folder so I think it needs to require `../dist/react-native/pusher`.

Happy to put this in another issue if it is unrelated.

**Comment by leesio** [comment]
You're absolutely correct @special-character, good spot and thanks for the PR

**Comment by leesio** [comment]
@special-character I just pushed 6.0.2, can you confirm that fixes things for you?

**Comment by special-character** [comment]
@leesio Thanks for releasing so quickly. That resolved the issue for me!

**Comment by calebdre** [comment]
@leesio I'm on version `6.0.2`, but I'm getting a different error: 
`Unable to resolve "runtime" from "node_modules/pusher-js/src/core/pusher.ts"`

**Comment by calebdre** [comment]
Seems like the imports are off. The imports expect `pusher-js/src` to be the root, but it stops complaining when given relative imports

**Comment by leesio** [comment]
@calebdre could you describe where you're seeing this error?

**Comment by calebdre** [comment]
@leesio I'm seeing it when I run my react native app. It tries to load the javascript bundle but then it runs into these errors

**Comment by calebdre** [comment]
@leesio false alarm - just found it was a bug in my code. was importing `logger` from pusher  for some reason 😅

**Comment by leesio** [comment]
I'm going to close this issue as it seems to be resolved. Feel free to reopen if I'm mistaken
