### ISSUE TITLE
Cannot find module on build

### ISSUE THREAD

**Issue by alboltdrogo** [pusher/pusher-js#424]
Since our upgrade to angular 9, we receive the following errors when trying to build the application:

```
ERROR in node_modules/pusher-js/types/src/core/pusher.d.ts:1:29 - error TS2307: Cannot find module 'runtimes/interface'.

1 import AbstractRuntime from 'runtimes/interface';
                              ~~~~~~~~~~~~~~~~~~~~
node_modules/pusher-js/types/src/runtimes/interface.d.ts:1:32 - error TS2307: Cannot find module 'core/auth/auth_transports'.

1 import { AuthTransports } from 'core/auth/auth_transports';
                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~
node_modules/pusher-js/types/src/runtimes/interface.d.ts:2:31 - error TS2307: Cannot find module 'core/timeline/timeline_transport'.

2 import TimelineTransport from 'core/timeline/timeline_transport';
                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
node_modules/pusher-js/types/src/runtimes/interface.d.ts:3:18 - error TS2307: Cannot find module 'core/http/ajax'.

3 import Ajax from 'core/http/ajax';
                   ~~~~~~~~~~~~~~~~
node_modules/pusher-js/types/src/runtimes/interface.d.ts:4:26 - error TS2307: Cannot find module 'core/reachability'.

4 import Reachability from 'core/reachability';
                           ~~~~~~~~~~~~~~~~~~~
node_modules/pusher-js/types/src/runtimes/interface.d.ts:5:29 - error TS2307: Cannot find module 'core/transports/transports_table'.

5 import TransportsTable from 'core/transports/transports_table';
                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
node_modules/pusher-js/types/src/runtimes/interface.d.ts:6:20 - error TS2307: Cannot find module 'core/socket'.

6 import Socket from 'core/socket';
                     ~~~~~~~~~~~~~
node_modules/pusher-js/types/src/runtimes/interface.d.ts:7:25 - error TS2307: Cannot find module 'core/http/http_factory'.

7 import HTTPFactory from 'core/http/http_factory';
                          ~~~~~~~~~~~~~~~~~~~~~~~~
node_modules/pusher-js/types/src/runtimes/interface.d.ts:8:25 - error TS2307: Cannot find module 'core/http/http_request'.

8 import HTTPRequest from 'core/http/http_request';
                          ~~~~~~~~~~~~~~~~~~~~~~~~
node_modules/pusher-js/types/src/runtimes/interface.d.ts:9:20 - error TS2307: Cannot find module 'core/pusher'.

9 import Pusher from 'core/pusher';
                     ~~~~~~~~~~~~~
node_modules/pusher-js/types/src/runtimes/interface.d.ts:11:22 - error TS2307: Cannot find module 'core/strategies/strategy'.

11 import Strategy from 'core/strategies/strategy';
                        ~~~~~~~~~~~~~~~~~~~~~~~~~~

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! snowhat@0.0.0 build:client-and-server-bundles: `ng build --configuration=test && ng run snowhat:server --bundleDependencies all`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the snowhat@0.0.0 build:client-and-server-bundles script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/deployer/.npm/_logs/2020-02-12T09_35_44_319Z-debug.log
```

Any clue what causes this and how we can make it work?

**Comment by leesio** [comment]
Hey @alboltdrogo, thanks for highlighting this.

Is this with pusher-js v5.1.0? Is the issue the same with v5.0.3? I deployed version 5.1.0 yesterday and it included type declarations. I'm wondering whether that's affecting your build.

**Comment by alboltdrogo** [comment]
Thank you for the fast reply.

We were still on v5.0.3, I just upgraded to 5.1.0 but unfortunately the issue remains.

**Comment by leesio** [comment]
Are you certain the issue existed in v5.0.3? It seems like the stack you sent concerns code that wasn't presence in 5.0.3.

I wonder whether you could confirm by fixing the version in `package.json`. 

```
"pusher-js" : "5.0.3"
```
(note: no `~` or `^`)

**Comment by alboltdrogo** [comment]
You are right, when setting it back to v5.0.3 explicitly it builds fine.

It seems to expect a relative path in order to work.

This works fine:
```import AbstractRuntime from '../runtimes/interface';```
This doesn't:
```import AbstractRuntime from 'runtimes/interface';```

**Comment by leesio** [comment]
OK - I'll spend some time looking into this issue. In the meantime are you happy sticking with version 5.0.3 as a workaround?

**Comment by leesio** [comment]
@alboltdrogo I just pushed a change that I think may help - if you have the time I'd be interested to see whether the branch `fix-ts-declarations` works in your build.

You can install it with

`npm install git+ssh://git@github.com:pusher/pusher-js#fix-ts-declarations`

If this fixes your issue I'll get it merged and deployed ASAP

**Comment by alboltdrogo** [comment]
The branch works fine. Thank you for the quick fix :)

**Comment by thegnuu** [comment]
Just had the same issue and I can confirm as well that the branch `fix-ts-declarations` works!

**Comment by leesio** [comment]
I just created release 5.1.1 and published to `npm`, can anybody confirm whether everything is working as expected?

**Comment by thegnuu** [comment]
Just updated to `5.1.1` and it works without any issues in my project :) 

Thank you very much!

**Comment by leesio** [comment]
I'm going to close this issue as it seems to be resolved
