### ISSUE TITLE
Keep getting "Invalid channel name"

### ISSUE THREAD

**Issue by herzaso** [pusher/pusher-js#684]
Using version 5.1.2 in node in the server (v18.12.1), I get this error: `Error: Invalid channel name: '1673738400000'`.
I'm using the same code from https://pusher.com/docs/channels/getting_started/javascript/#trigger-events-from-your-server
According to the documents, numbers are permitted in channel name, so I expected it to work

**Comment by herzaso** [comment]
The error is in the server:
```
/srb-api/node_modules/pusher/lib/pusher.js:20
    throw new Error("Invalid channel name: '" + channel + "'")
    ^

Error: Invalid channel name: '1673738400000'
    at validateChannel (/srb-api/node_modules/pusher/lib/pusher.js:20:11)
    at Pusher.trigger (/srb-api/node_modules/pusher/lib/pusher.js:220:5)
    at broadcast (file:///srb-api/api.js:93:17)
    at levelStart (file:///srb-api/api.js:138:3)
    at Timeout._onTimeout (file:///srb-api/api.js:224:42)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)

Node.js v18.12.1
```

pusher v5.1.2

**Comment by benw-pusher** [comment]
Thanks for the update - this issue was raised on the JS lib and not the node-js lib, hence my confusion. I can see the offending code in the library, will investigate further and get back to you.

**Comment by herzaso** [comment]
Thanks @benw-pusher. I just noticed that this issue was fixed. I will test it on the next release.

**Comment by benw-pusher** [comment]
@herzaso the issue wasn't fixed - I closed the PR as I had a misunderstanding. I am still investigating.

**Comment by benw-pusher** [comment]
Thanks @herzaso , i'll close off but if you go back to this and encounter the issue once again feel free to get in touch at 
https://support.pusher.com/hc/en-us/requests/new
